project:
  type: website
  output-dir: docs

website:
  title: "**The Nevin Scoop** | petebrown.codes"
  site-url: https://petebrown.codes
  description: "Pete Brown's blog, mostly compromised of data analysis of Tranmere Rovers using Python and R."
  navbar:
    right:
      - text: "Apps"
        menu:
        - text: "Season Tracker"
          href: apps/season-tracker
        - text: "Head-to-Head: All teams"
          href: apps/head2head-all
        - text: "Head-to-Head: Individual teams"
          href: apps/head2head
        - text: "Managerial records: All managers"
          href: apps/managers-all
        - text: "Managerial records: Individual managers"
          href: apps/managers
        - text: "Attendances: Overall records"
          href: apps/attendances
        - text: "Attendances: Compare by season"
          href: apps/attendances-by-season
      - archive.qmd
      - about.qmd
      - icon: github
        href: https://github.com/petebrown
      - icon: twitter
        href: https://twitter.com/beteprown
      - icon: rss
        href: sitemap.xml
format:
  html:
    # theme: flatly
    theme: theme.scss
    #css: theme.css
    mainfont: "Helvetica Neue, Open Sans"
    title-block-style: default
    title-block-banner: 'white'
    title-block-banner-color: 'black'
    title-block-categories: false