project:
  type: website
  output-dir: docs

website:
  title: "The Nevin Scoop"
  site-url: https://petebrown.codes
  description: "Pete Brown's blog, mostly compromised of data analysis of Tranmere Rovers using Python and R."
  navbar:
    right:
      - archive.qmd
      - about.qmd
      - icon: github
        href: https://github.com/petebrown
      - icon: twitter
        href: https://twitter.com/beteprown
      - icon: rss
        href: sitemap.xml
format:
  html:
    # theme: flatly
    theme: theme.scss
    #css: theme.css
    header-includes: <link rel="stylesheet" media="screen" href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,300" type="text/css"/>
    mainfont: "Helvetica Neue, Open Sans"
    title-block-style: default
    title-block-banner: 'white'
    title-block-banner-color: 'black'
    title-block-categories: false